### ISSUE TITLE
Add README file 

### ISSUE THREAD

**Issue by Asymmentric** [Asymmentric/oslLogBook#1]
README file for the project is missing.

**Comment by tyler-le** [comment]
i can do this

**Comment by Asymmentric** [comment]
@tyler-le you can proceed with it

**Comment by tyler-le** [comment]
@Asymmentric  
do you want me to put content in the readme or do you want me to simply make an empty readme file?

**Comment by Asymmentric** [comment]
It would be really great if you would put content also.
You can go through the working of the project and update the readme accordingly.
