### ISSUE TITLE
Improve fronted UI and design pages

### ISSUE THREAD

**Issue by Asymmentric** [Asymmentric/oslLogBook#2]
UI of the project is very primitive and simple. It can be improved to look good

**Comment by k-deepak04** [comment]
#9 updated the Login and added styles and created a PR

**Comment by k-deepak04** [comment]
@Asymmentric it would be great if you can mention properly in which pages you want to update the UI. 
I will look into that then specifically.
If you want i can create issue. Shall I? :)
