### ISSUE TITLE
Remove and accept changes from scripts

### ISSUE THREAD

**Issue by Hi-Pyncho** [Asymmentric/oslLogBook#7]
There are a lot of lines from older pull requests like `<<<<<<< HEAD` and another
For example, in the `server.js` [file](https://github.com/Asymmentric/oslLogBook/blob/main/server/server.js) or in [this file](https://github.com/Asymmentric/oslLogBook/blob/main/server/util/pwdFunc.js)
Because of that you can't run project without errors

I could do it, but owner have to choose what code need to remove and save

**Comment by Asymmentric** [comment]
Thankyou @Hi-Pyncho for pointing out the issues. I have been working on resolving the issue.

**Comment by Asymmentric** [comment]
@Hi-Pyncho it would be really helpful if you could re-check to see if the issue still persists.

**Comment by Hi-Pyncho** [comment]
@Asymmentric it's okey now :)
